### ISSUE TITLE
about memory_feat_comic.pkl

### ISSUE THREAD

**Issue by Hyouka-qitanta** [hitachi-rd-cv/MILA#3]
when i train the model i got the follow error:

 Traceback (most recent call last):
  File "train_net_mem.py", line 77, in <module>
    launch(
  File "/home/zhengguida/miniconda3/envs/MILA/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net_mem.py", line 70, in main
    return trainer.train()
  File "/home/zhengguida/MILA/memory/engine/trainer_mem.py", line 205, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/home/zhengguida/MILA/memory/engine/trainer_mem.py", line 224, in train_loop
    self.run_step_full_semisup()
  File "/home/zhengguida/MILA/memory/engine/trainer_mem.py", line 385, in run_step_full_semisup
    file = open("memory_feat_comic.pkl",'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'memory_feat_comic.pkl'

how to get the memory_feat_comic.pkl file?

**Comment by onkarkris** [comment]
Sorry for the confusion. We don't need any pkl file to run this code; that was only for debugging purpose. I have updated trainer_mem.py; you should be able to run it without any issues now!

**Comment by Hyouka-qitanta** [comment]
> Sorry for the confusion. We don't need any pkl file to run this code; that was only for debugging purpose. I have updated trainer_mem.py; you should be able to run it without any issues now!

Thank you for your prompt reply, i run the code successfully. 
 I found the MAX_ITER in faster_rcnn_R101_cross_comic_08032.yaml file is 200000, it's too much and need almost 15 days to train on A100 GPU. I want to know does it really need to train 200000 iterations or just a mistake?
